### ISSUE TITLE
When using a primary key with a passphrase, signing of a key doesn't work

### ISSUE THREAD

**Issue by andreimacavei** [andreimacavei/geysigning#20]
I receive a `gpgme.GpgmeError: (32, 1, u'General error')` error when I run the app and I press `Next` when it asks me if I want to sign the downloaded key. 
This is happening in the same time with the pop-up window spawn by `gnome-session` or `gpg-agent` to enter the passphrase for the primary key used to sign.

Here is the traceback that I receive:

```
Traceback (most recent call last):
  File "/home/andrei/projects/gnome-keysign/keysign/Sections.py", line 425, in sign_key_async
    res = gpg.gpg_sign_uid(ctx, gpg_homedir, uid)
  File "/home/andrei/projects/gnome-keysign/keysign/gpg/gpg.py", line 181, in gpg_sign_uid
    gpgme.editutil.edit_sign(gpgmeContext, key, index=i, check=0)
  File "/usr/lib/python2.7/dist-packages/gpgme/editutil.py", line 75, in wrapper
    ctx.edit(key, edit_callback, output)
gpgme.GpgmeError: (32, 1, u'General error')
```

**Comment by igor-raits** [comment]
https://pagure.io/pygpgme/c/f14699792622715c9cec372400f9dc38f1122f63
